const TOPICS={
 algebra:{name:"Algebraic expressions",term:1,summary:"Real numbers, expansion, factorisation and algebraic fractions",worked:"Factorise x² − 5x + 6 by finding two numbers that multiply to 6 and add to −5. They are −2 and −3, so x² − 5x + 6 = (x − 2)(x − 3)."},
 equations:{name:"Exponents & equations",term:1,summary:"Exponent laws, equations, inequalities and changing the subject",worked:"For 2³ × 2⁴, keep the base and add the exponents: 2³⁺⁴ = 2⁷ = 128."},
 trig:{name:"Trigonometry",term:1,summary:"Trig ratios, special angles and right-angled triangles",worked:"If opposite = 6 and hypotenuse = 10, sin θ = 6/10 = 0.6. Therefore θ = sin⁻¹(0.6) ≈ 36.9°."},
 euclidean:{name:"Euclidean geometry",term:2,summary:"Triangles, quadrilaterals, midpoint theorem and riders",worked:"Opposite sides of a parallelogram are parallel and equal. Use these properties together with angle facts, and always give a reason for each statement."},
 analytical:{name:"Analytical geometry",term:2,summary:"Distance, gradient and midpoint",worked:"Between A(2,1) and B(6,9), gradient = (9−1)/(6−2) = 8/4 = 2. The midpoint is ((2+6)/2,(1+9)/2) = (4,5)."},
 functions:{name:"Functions & graphs",term:2,summary:"Shape, domain, range, intercepts, asymptotes and transformations",worked:"For y = 2x − 4, the y-intercept is −4. Set y=0 to find the x-intercept: 0=2x−4, so x=2."},
 statistics:{name:"Statistics",term:3,summary:"Central tendency, spread, quartiles, box plots and histograms",worked:"For 2, 3, 3, 7, 10: mean=25/5=5, median=3, mode=3 and range=10−2=8."},
 probability:{name:"Probability",term:3,summary:"Relative frequency, Venn diagrams, unions and complements",worked:"If P(A)=0.55, P(B)=0.35 and P(A and B)=0.15, then P(A or B)=0.55+0.35−0.15=0.75."},
 finance:{name:"Finance & growth",term:3,summary:"Simple and compound growth in real contexts",worked:"For R2 000 invested at 8% compound interest for 3 years: A=2000(1.08)³=R2 519.42."},
 measurement:{name:"Measurement",term:4,summary:"Surface area and volume of three-dimensional objects",worked:"A cylinder with r=3 cm and h=5 cm has volume V=πr²h=π(3²)(5)=45π≈141.37 cm³."},
 patterns:{name:"Number patterns",term:4,summary:"Linear patterns and general terms",worked:"In 5, 8, 11, 14, … the common difference is 3. Tₙ=3n+2 because T₁=5."}
};
const QUESTIONS=[
 q("algebra","Which is the factorised form of x² − 9?",["(x−9)(x+1)","(x−3)(x+3)","(x−3)²","x(x−9)"],1,"Use the difference of two squares: a²−b²=(a−b)(a+b)."),
 q("algebra","Simplify 3x(2x − 5).",["6x²−15x","6x−15","5x²−15x","6x²−5"],0,"Multiply 3x by every term inside the bracket."),
 q("equations","Simplify a⁵ ÷ a².",["a¹⁰","a⁷","a³","a²⋅⁵"],2,"When dividing like bases, subtract exponents."),
 q("equations","Solve 3x − 7 = 11.",["x=4","x=6","x=8","x=18"],1,"Add 7 to both sides, then divide by 3."),
 q("trig","In a right triangle, which ratio is opposite/hypotenuse?",["tan θ","cos θ","sin θ","sec θ"],2,"SOH: sin = opposite ÷ hypotenuse."),
 q("trig","If tan θ = 1 and 0°≤θ≤90°, what is θ?",["30°","45°","60°","90°"],1,"tan 45°=1."),
 q("euclidean","The diagonals of a parallelogram…",["are always equal","bisect each other","meet at 90° always","never intersect"],1,"A core parallelogram property is that its diagonals bisect one another."),
 q("euclidean","Angles on a straight line add up to…",["90°","180°","270°","360°"],1,"A straight angle measures 180°."),
 q("analytical","Find the gradient through (1,2) and (5,10).",["1/2","2","4","8"],1,"m=(10−2)/(5−1)=8/4=2."),
 q("analytical","Find the midpoint of (2,4) and (8,10).",["(5,7)","(6,6)","(10,14)","(3,9)"],0,"Average the x-values and the y-values separately."),
 q("functions","What is the y-intercept of y=3x−6?",["3","−6","2","−2"],1,"At the y-intercept x=0."),
 q("functions","Which graph has an asymptote at x=0?",["y=x","y=x²","y=1/x","y=2x+1"],2,"The hyperbola y=1/x is undefined at x=0."),
 q("statistics","Find the median of 2, 4, 7, 9, 12.",["4","6.8","7","9"],2,"The median is the middle ordered value."),
 q("statistics","Find the range of 5, 8, 13, 19.",["11","14","19","45"],1,"Range=maximum−minimum=19−5."),
 q("probability","A fair die is rolled. P(even number) is…",["1/6","1/3","1/2","2/3"],2,"There are 3 even outcomes out of 6."),
 q("probability","If P(A)=0.3, what is P(not A)?",["0.3","0.5","0.7","1.3"],2,"Complementary probabilities add to 1."),
 q("finance","Which formula represents compound growth?",["A=P(1+in)","A=P(1+i)ⁿ","A=P+i+n","A=Pin"],1,"Compound growth applies the growth factor repeatedly."),
 q("finance","R1 000 grows by 10% simple interest for 2 years. A is…",["R1 100","R1 200","R1 210","R2 000"],1,"A=P(1+in)=1000(1+0.10×2)."),
 q("measurement","The volume of a cylinder is…",["πr²h","2πr","πrh","⅓πr²h"],0,"Volume of a cylinder=area of circular base×height."),
 q("measurement","If every dimension doubles, volume is multiplied by…",["2","4","6","8"],3,"Volume changes by k³, so 2³=8."),
 q("patterns","Find the next term: 4, 9, 14, 19, …",["20","23","24","29"],2,"The constant difference is 5."),
 q("patterns","For Tₙ=4n−1, find T₅.",["15","19","20","21"],1,"Substitute n=5: 4(5)−1=19.")
];
const FOLLOWUPS=[
 q("algebra","Expand and simplify −2x(3x − 4).",["−6x²+8x","−6x²−8x","−6x+8","6x²−8x"],0,"A negative multiplied by a negative becomes positive.","signs and distribution"),
 q("equations","Solve −2x + 5 = 13.",["x=−4","x=4","x=−9","x=9"],0,"Subtract 5 first, then divide by −2.","signs and inverse operations"),
 q("trig","A right triangle has opposite=8 and adjacent=6. Which setup finds θ?",["sin θ=8/6","cos θ=8/6","tan θ=8/6","tan θ=6/8"],2,"Opposite and adjacent use tan.","ratio selection"),
 q("euclidean","Two parallel lines are cut by a transversal. If one corresponding angle is 68°, the matching angle is…",["22°","68°","112°","292°"],1,"Corresponding angles between parallel lines are equal.","geometry reasons"),
 q("analytical","Find the distance between (1,1) and (4,5).",["3","4","5","7"],2,"Use √[(4−1)²+(5−1)²].","substitution and calculation"),
 q("functions","For y=−2x+6, find the x-intercept.",["−3","2","3","6"],2,"At the x-intercept, set y=0.","intercepts and substitution"),
 q("statistics","Find the mean of 4, 6, 8 and 10.",["6","7","8","28"],1,"Add all values and divide by four.","mean calculation"),
 q("probability","If P(A)=0.6, P(B)=0.5 and P(A and B)=0.2, find P(A or B).",["0.9","1.1","0.7","0.3"],0,"Add P(A) and P(B), then subtract the overlap.","union and overlap"),
 q("finance","R2 000 grows at 5% compound interest for 2 years. The correct setup is…",["2000(1+0.05×2)","2000(1.05)²","2000(0.05)²","2000+0.05²"],1,"Compound growth uses A=P(1+i)ⁿ.","formula and substitution"),
 q("measurement","Find the volume of a cylinder with r=2 cm and h=5 cm.",["10π cm³","20π cm³","25π cm³","40π cm³"],1,"V=πr²h=π(2²)(5).","formula and calculation"),
 q("patterns","The sequence 7, 11, 15, 19,… has general term…",["4n+3","4n−3","7n+4","3n+4"],0,"Use Tₙ=dn+(first term−d).","general term")
];
function q(topic,text,options,answer,help,skill){return{topic,text,options,answer,help,skill:skill||null,followUp:Boolean(skill)}}
const ISSUE_BY_TOPIC={algebra:"algebraic signs or distribution",equations:"inverse operations or signs",trig:"ratio or calculator selection",euclidean:"geometry property or reason",analytical:"formula substitution or arithmetic",functions:"graph feature or substitution",statistics:"statistical method or arithmetic",probability:"probability rule or overlap",finance:"formula selection or percentage substitution",measurement:"formula selection or units",patterns:"common difference or general term"};
const state={view:"home",profile:null,quiz:[],index:0,answers:[],workings:[],followedTopics:new Set(),supportTopic:null,practiceQueue:[],practiceIndex:0,canvas:null,canvasCtx:null,drawing:false,eraser:false,lastPoint:null,inkDistance:0,strokeCount:0,hasWorkingEvidence:false,dashboardRecords:[]};
const app=document.querySelector("#app"),homeBtn=document.querySelector("#homeBtn");
const db={get:()=>JSON.parse(localStorage.getItem("mathsPathwayLearners")||"[]"),set:v=>localStorage.setItem("mathsPathwayLearners",JSON.stringify(v))};
const cloud=window.supabase?window.supabase.createClient("https://hpyebkifbcwbywmscyuq.supabase.co","sb_publishable_Mf1mGlkRCgyk2baXvcFd1Q_qOBCX7iE"):null;
homeBtn.onclick=()=>renderHome();
function shell(content,showHome=true){app.innerHTML=content;homeBtn.classList.toggle("hidden",!showHome);window.scrollTo({top:0,behavior:"smooth"})}
function renderHome(){state.view="home";shell(`<section class="hero"><span class="eyebrow">Know your gaps. Build your confidence.</span><h1>Your personalised Grade 10 Maths pathway.</h1><p>Start with a short diagnostic. The app finds the topics that need attention and gives you focused support, worked examples and practice.</p><div class="role-grid"><button class="role-card" onclick="showLearnerStart()"><span class="role-icon">✦</span><h3>I’m a learner</h3><p>Take a diagnostic or continue your support pathway.</p><span class="btn">Start learning</span></button><button class="role-card" onclick="showDashboard()"><span class="role-icon">◫</span><h3>Facilitator dashboard</h3><p>View learner mastery, gaps and recommended next steps.</p><span class="btn gold">Open dashboard</span></button></div></section>`,false)}
function showLearnerStart(){const learners=db.get();shell(`<div class="screen-head"><div><span class="eyebrow">Learner space</span><h2>Let’s find your next step</h2></div></div><section class="panel form-card"><div class="field"><label>Your name</label><input id="learnerName" placeholder="Enter first and last name"></div><div class="field"><label>Class</label><select id="learnerClass"><option>Grade 10.1</option><option>Grade 10.2</option><option>Grade 10</option></select></div><button class="btn" onclick="beginDiagnostic()">Begin diagnostic</button>${learners.length?`<p class="muted">Returning learner? Use the same name to update your profile.</p>`:""}</section>`)}
function beginDiagnostic(){const name=document.querySelector("#learnerName").value.trim();if(!name)return alert("Please enter the learner’s name.");state.profile={name,className:document.querySelector("#learnerClass").value};state.quiz=[...QUESTIONS].sort(()=>Math.random()-.5);state.index=0;state.answers=[];state.workings=[];state.followedTopics=new Set();renderQuestion()}
function workingCanvas(){return `<div class="working-wrap"><div class="working-head"><strong>Show every step or write your reason</strong><div class="canvas-tools"><button id="penBtn" class="tool-btn active" onclick="setCanvasTool(false)">Pen</button><button id="eraseBtn" class="tool-btn" onclick="setCanvasTool(true)">Eraser</button><button class="tool-btn" onclick="clearCanvas()">Clear</button></div></div><canvas id="workCanvas" class="work-canvas"></canvas><div id="workingStatus" class="working-note">Write in the space before choosing an answer.</div></div>`}
function renderQuestion(){const item=state.quiz[state.index],pct=Math.round(state.index/state.quiz.length*100);shell(`<div class="screen-head"><div><span class="eyebrow">Adaptive diagnostic</span><h2>Question ${state.index+1} of ${state.quiz.length}</h2></div><span class="pill ${item.followUp?"red":"orange"}">${item.followUp?"Extra check · ":""}${TOPICS[item.topic].name}</span></div><div class="progress-track"><div class="progress-bar" style="width:${pct}%"></div></div><section class="panel" style="margin-top:20px"><p class="question">${item.text}</p>${workingCanvas()}<div class="options">${item.options.map((o,i)=>`<button class="option answer-choice" disabled onclick="chooseAnswer(${i})">${String.fromCharCode(65+i)}. ${o}</button>`).join("")}</div><div id="answerGate" class="notice">Complete enough written working to unlock the answers.</div><div id="diagnosticFeedback"></div></section>`);setupCanvas()}
async function chooseAnswer(choice){
 if(!state.hasWorkingEvidence){document.querySelector("#answerGate").textContent="Please show your calculation or written reason first.";return}
 const item=state.quiz[state.index],working=captureCanvas(),feedback=document.querySelector("#diagnosticFeedback");
 document.querySelectorAll(".answer-choice").forEach(b=>b.disabled=true);
 document.querySelector("#answerGate").classList.add("hidden");
 feedback.innerHTML='<div class="notice"><strong>Checking your written method…</strong><br>Please wait a moment.</div>';
 const aiAnalysis=await analyseMathsWorking(item,choice,working);
 if(aiAnalysis&&!aiAnalysis.enoughWorking){
  feedback.innerHTML=`<div class="answer-feedback incorrect"><strong>More working is needed.</strong><br>${safeText(aiAnalysis.feedback)}<br><small>${safeText(aiAnalysis.nextStep)}</small></div><button class="btn" style="margin-top:12px" onclick="renderQuestion()">Rewrite my working</button>`;
  return;
 }
 const correct=choice===item.answer,issue=diagnosticIssue(item,correct,aiAnalysis);
 state.workings.push(working);
 state.answers.push({topic:item.topic,correct,choice,issue,skill:item.skill,followUp:item.followUp,aiAnalysis});
 const methodConcern=Boolean(aiAnalysis&&aiAnalysis.errorCategory&&aiAnalysis.errorCategory!=="correct_method");
 if((!correct||methodConcern)&&!item.followUp&&!state.followedTopics.has(item.topic)){const probe=FOLLOWUPS.find(q=>q.topic===item.topic);if(probe){state.quiz.splice(state.index+1,0,probe);state.followedTopics.add(item.topic)}}
 const message=aiAnalysis?`${safeText(aiAnalysis.feedback)}<br><small>${safeText(aiAnalysis.nextStep)}</small>`:(correct?"Your written method has been recorded.":safeText(item.help));
 feedback.innerHTML=`<div class="answer-feedback ${correct?"correct":"incorrect"}"><strong>${correct?"Correct—well done.":"Let’s check this carefully."}</strong><br>${message}</div><button class="btn" style="margin-top:12px" onclick="advanceDiagnostic()">${state.index===state.quiz.length-1?"See my pathway":"Next question"}</button>`;
}
function advanceDiagnostic(){state.index++;state.index<state.quiz.length?renderQuestion():finishDiagnostic()}
function finishDiagnostic(){const totals={},issues={};Object.keys(TOPICS).forEach(k=>totals[k]={correct:0,total:0});state.answers.forEach(a=>{totals[a.topic].total++;if(a.correct)totals[a.topic].correct++;if(a.issue)issues[a.issue]=(issues[a.issue]||0)+1});const scores={};Object.entries(totals).forEach(([k,v])=>scores[k]=v.total?Math.round(v.correct/v.total*100):0);const overall=Math.round(state.answers.filter(a=>a.correct).length/state.answers.length*100),weakest=Object.keys(scores).sort((a,b)=>scores[a]-scores[b])[0],issueSummary=Object.entries(issues).sort((a,b)=>b[1]-a[1]).map(([name,count])=>({name,count}));const learners=db.get(),key=state.profile.name.toLowerCase(),evidence=state.answers.map((a,i)=>({...a,question:state.quiz[i].text,selectedAnswer:state.quiz[i].options[a.choice],correctAnswer:state.quiz[i].options[state.quiz[i].answer],working:state.workings[i]}));const record={...state.profile,lastAttempt:new Date().toISOString(),overall,scores,recommended:weakest,attempts:1,evidence,issueSummary};const old=learners.find(l=>l.name.toLowerCase()===key);if(old)record.attempts=(old.attempts||0)+1;db.set([...learners.filter(l=>l.name.toLowerCase()!==key),record]);state.profile=record;submitOnlineRecord({learner_name:record.name,class_name:record.className,record_type:"diagnostic",topic:record.recommended,overall_score:record.overall,topic_scores:record.scores,evidence:record.evidence});renderResults()}
function band(n){return n>=75?["Secure","green"]:n>=50?["Developing","orange"]:["Priority","red"]}
function renderResults(){const p=state.profile,ordered=Object.keys(p.scores).sort((a,b)=>p.scores[a]-p.scores[b]),issues=p.issueSummary||[];shell(`<div class="screen-head"><div><span class="eyebrow">Your pathway</span><h2>${p.name}, here’s what we found</h2></div></div><section class="panel"><div class="result-top"><div class="score-ring" style="--score:${p.overall}"><strong>${p.overall}%</strong></div><div><h3>Diagnostic complete</h3><p class="muted">Your first focus is <strong>${TOPICS[p.recommended].name}</strong>. Practice will also revisit secure topics so that you keep them strong.</p><button class="btn" onclick="openSupport('${p.recommended}')">Start balanced practice</button></div></div>${issues.length?`<div class="notice" style="margin-top:18px"><strong>Possible barriers to check:</strong> ${issues.slice(0,3).map(i=>safeText(i.name)).join(" · ")}. Your facilitator will compare these clues with your written working.</div>`:""}</section><div class="cards"><section class="panel"><h3>Topic map</h3>${ordered.map(k=>{const [label,color]=band(p.scores[k]);return`<div class="topic-row"><div><strong>${TOPICS[k].name}</strong><br><small class="muted">Term ${TOPICS[k].term}</small></div><div class="mini-track"><span style="width:${p.scores[k]}%"></span></div><span class="pill ${color}">${label}</span></div>`}).join("")}</section><section class="panel"><h3>Complete learning pathway</h3><p class="muted">Priority topics come first. Secure topics remain in the cycle as memory checks.</p>${ordered.map((k,i)=>`<div class="lesson-step"><small class="eyebrow">${p.scores[k]>=75?"Keep fresh":"Focus"} · Step ${i+1}</small><h3>${TOPICS[k].name}</h3><p class="muted">${TOPICS[k].summary}</p><button class="btn secondary" onclick="openSupport('${k}')">Practise</button></div>`).join("")}</section></div>`)}
function openSupport(topic){state.supportTopic=topic;const all=[...QUESTIONS,...FOLLOWUPS],focus=shuffle(all.filter(q=>q.topic===topic)).slice(0,3),strong=state.profile?Object.keys(state.profile.scores).filter(k=>k!==topic&&state.profile.scores[k]>=75):[],reviewPool=all.filter(q=>q.topic!==topic&&(strong.length?strong.includes(q.topic):true));state.practiceQueue=[...focus,...shuffle(reviewPool).slice(0,2)];state.practiceIndex=0;renderPracticeQuestion()}
function renderPracticeQuestion(){if(state.practiceIndex>=state.practiceQueue.length)return renderPracticeComplete();const item=state.practiceQueue[state.practiceIndex],isFocus=item.topic===state.supportTopic,t=TOPICS[state.supportTopic];shell(`<div class="screen-head"><div><span class="eyebrow">Balanced practice · ${state.practiceIndex+1} of ${state.practiceQueue.length}</span><h2>${isFocus?t.name:"Keep fresh: "+TOPICS[item.topic].name}</h2><p class="muted">${isFocus?t.summary:"A short memory check from another part of the course."}</p></div><span class="pill ${isFocus?"orange":"green"}">${isFocus?"Targeted support":"Spaced review"}</span></div><div class="progress-track"><div class="progress-bar" style="width:${Math.round(state.practiceIndex/state.practiceQueue.length*100)}%"></div></div>${state.practiceIndex===0?`<section class="panel" style="margin-top:18px"><h3>Worked example</h3><div class="worked equation">${t.worked}</div></section>`:""}<section class="panel" style="margin-top:18px"><p class="question">${item.text}</p>${workingCanvas()}<div class="options">${item.options.map((o,i)=>`<button class="option answer-choice" disabled onclick="supportAnswer(${i})">${o}</button>`).join("")}</div><div id="answerGate" class="notice">Show your written method to unlock the answers.</div><div id="supportFeedback"></div></section>`);setupCanvas()}
async function supportAnswer(choice){
 if(!state.hasWorkingEvidence)return;
 const item=state.practiceQueue[state.practiceIndex],working=captureCanvas(),feedback=document.querySelector("#supportFeedback");
 document.querySelectorAll(".answer-choice").forEach(b=>b.disabled=true);
 document.querySelector("#answerGate").classList.add("hidden");
 feedback.innerHTML='<div class="notice"><strong>Checking your written method…</strong><br>Please wait a moment.</div>';
 const aiAnalysis=await analyseMathsWorking(item,choice,working);
 if(aiAnalysis&&!aiAnalysis.enoughWorking){
  feedback.innerHTML=`<div class="answer-feedback incorrect"><strong>More working is needed before you continue.</strong><br>${safeText(aiAnalysis.feedback)}<br><small>${safeText(aiAnalysis.nextStep)}</small></div><button class="btn" style="margin-top:12px" onclick="renderPracticeQuestion()">Rewrite my working</button>`;
  return;
 }
 const ok=choice===item.answer,issue=diagnosticIssue(item,ok,aiAnalysis);
 saveSupportEvidence(item,choice,ok,working,issue,aiAnalysis);
 const detail=aiAnalysis?`${safeText(aiAnalysis.feedback)}<br><small>${safeText(aiAnalysis.nextStep)}</small>`:safeText(item.help);
 feedback.innerHTML=`<div class="answer-feedback ${ok?"correct":"incorrect"}"><strong>${ok?"Correct—well done.":"Not yet. Possible difficulty: "+safeText(issue)+"."}</strong><br>${detail}</div><button class="btn" style="margin-top:12px" onclick="nextPracticeQuestion()">${state.practiceIndex===state.practiceQueue.length-1?"Finish session":"Next question"}</button>`
}
function nextPracticeQuestion(){state.practiceIndex++;renderPracticeQuestion()}
function renderPracticeComplete(){shell(`<section class="panel form-card"><span class="eyebrow">Session complete</span><h2>Focused work and memory practice done</h2><p class="muted">Your session included the target topic and questions from other topics to help prevent forgetting.</p><button class="btn" onclick="renderResults()">Return to my pathway</button></section>`)}
function shuffle(items){return [...items].sort(()=>Math.random()-.5)}
function showDashboard(){const learners=db.get();const avg=learners.length?Math.round(learners.reduce((s,l)=>s+l.overall,0)/learners.length):0;const priority=learners.filter(l=>l.overall<50).length;shell(`<div class="screen-head"><div><span class="eyebrow">Facilitator view</span><h2>Grade 10 Maths dashboard</h2><p class="muted">Diagnostic evidence and suggested support—not formal assessment marks.</p></div><button class="btn secondary" onclick="exportData()">Export learner data</button></div><div class="stat-grid"><div class="card stat"><span class="muted">Learners diagnosed</span><strong>${learners.length}</strong></div><div class="card stat"><span class="muted">Average mastery</span><strong>${avg}%</strong></div><div class="card stat"><span class="muted">Priority support</span><strong>${priority}</strong></div></div><section class="panel" style="margin-top:18px"><h3>Learner profiles</h3>${learners.length?`<div class="table-wrap"><table class="learner-table"><thead><tr><th>Learner</th><th>Class</th><th>Mastery</th><th>Priority topic</th><th>Attempts</th><th>Last activity</th></tr></thead><tbody>${learners.sort((a,b)=>a.overall-b.overall).map(l=>`<tr><td><strong>${l.name}</strong></td><td>${l.className}</td><td><span class="pill ${band(l.overall)[1]}">${l.overall}%</span></td><td>${TOPICS[l.recommended].name}</td><td>${l.attempts}</td><td>${new Date(l.lastAttempt).toLocaleDateString()}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty"><h3>No diagnostic results yet</h3><p>Once learners complete the diagnostic, their profiles will appear here.</p></div>`}</section><div class="notice" style="margin-top:16px"><strong>Pilot note:</strong> Data is saved on this browser. Use “Export learner data” to back it up or send it to the Maths teacher.</div>`)}
showDashboard=async function(){if(!cloud)return shell(`<section class="panel form-card"><h2>Internet connection needed</h2><p class="muted">Reconnect and refresh to open the secure facilitator dashboard.</p></section>`);const{data:{session}}=await cloud.auth.getSession();if(session)return loadOnlineDashboard();shell(`<section class="panel form-card"><span class="eyebrow">Secure facilitator access</span><h2 style="margin-top:10px">Dashboard sign in</h2><p class="muted">Use the facilitator email address and password registered for this app.</p><div class="field"><label>Email address</label><input id="facilitatorEmail" type="email" autocomplete="username" placeholder="name@example.com"></div><div class="field"><label>Password</label><input id="facilitatorPassword" type="password" autocomplete="current-password" placeholder="Enter password" onkeydown="if(event.key==='Enter')verifyFacilitatorLogin()"></div><div id="loginFeedback"></div><button class="btn" onclick="verifyFacilitatorLogin()">Sign in</button></section>`)};
async function verifyFacilitatorLogin(){const email=document.querySelector("#facilitatorEmail").value.trim(),password=document.querySelector("#facilitatorPassword").value,feedback=document.querySelector("#loginFeedback");feedback.innerHTML='<p class="muted">Signing in…</p>';const{error}=await cloud.auth.signInWithPassword({email,password});if(error){feedback.innerHTML='<div class="answer-feedback incorrect">The email address or password is incorrect.</div>'}else loadOnlineDashboard()}
async function loadOnlineDashboard(){shell(`<section class="panel"><h2>Loading learner records…</h2><p class="muted">Connecting to the secure dashboard.</p></section>`);const{data:records,error}=await cloud.from("learning_records").select("*").order("created_at",{ascending:false});if(error)return shell(`<section class="panel form-card"><h2>Dashboard unavailable</h2><div class="answer-feedback incorrect">${safeText(error.message)}</div><button class="btn secondary" onclick="facilitatorSignOut()">Sign out</button></section>`);renderOnlineDashboard(records||[])}
function renderOnlineDashboard(records){state.dashboardRecords=records;const diagnostics=records.filter(r=>r.record_type==="diagnostic"),latest=[];diagnostics.forEach(r=>{if(!latest.some(x=>x.learner_name.toLowerCase()===r.learner_name.toLowerCase()))latest.push(r)});const avg=latest.length?Math.round(latest.reduce((s,r)=>s+(r.overall_score||0),0)/latest.length):0,priority=latest.filter(r=>(r.overall_score||0)<50).length;shell(`<div class="screen-head"><div><span class="eyebrow">Live facilitator view</span><h2>Grade 10 Maths dashboard</h2><p class="muted">Open a learner’s evidence to compare their final answer with their handwritten method.</p></div><button class="btn secondary" onclick="facilitatorSignOut()">Sign out</button></div><div class="stat-grid"><div class="card stat"><span class="muted">Learners diagnosed</span><strong>${latest.length}</strong></div><div class="card stat"><span class="muted">Average mastery</span><strong>${avg}%</strong></div><div class="card stat"><span class="muted">Priority support</span><strong>${priority}</strong></div><div class="card stat"><span class="muted">Total activities</span><strong>${records.length}</strong></div></div><section class="panel" style="margin-top:18px"><h3>Learner profiles</h3>${latest.length?`<div class="table-wrap"><table class="learner-table"><thead><tr><th>Learner</th><th>Class</th><th>Mastery</th><th>Priority topic</th><th>Likely barrier</th><th>Evidence</th></tr></thead><tbody>${latest.sort((a,b)=>(a.overall_score||0)-(b.overall_score||0)).map(l=>{const barrier=(l.evidence||[]).find(e=>e.issue)?.issue||"Review working";return`<tr><td><strong>${safeText(l.learner_name)}</strong><br><small>${new Date(l.created_at).toLocaleDateString()}</small></td><td>${safeText(l.class_name)}</td><td><span class="pill ${band(l.overall_score||0)[1]}">${l.overall_score||0}%</span></td><td>${TOPICS[l.topic]?.name||safeText(l.topic||"—")}</td><td>${safeText(barrier)}</td><td><button class="btn secondary" onclick="viewLearnerEvidence(${l.id})">View working</button></td></tr>`}).join("")}</tbody></table></div>`:`<div class="empty"><h3>No online records yet</h3><p>New diagnostic submissions will appear here from any learner device.</p></div>`}</section>`)}
function viewLearnerEvidence(id){const record=state.dashboardRecords.find(r=>r.id===id);if(!record)return;const evidence=record.evidence||[];shell(`<div class="screen-head"><div><span class="eyebrow">Diagnostic evidence</span><h2>${safeText(record.learner_name)}</h2><p class="muted">${safeText(record.class_name)} · ${record.overall_score||0}% · ${new Date(record.created_at).toLocaleString()}</p></div><button class="btn secondary" onclick="renderOnlineDashboard(state.dashboardRecords)">Back to dashboard</button></div><div class="evidence-grid">${evidence.map((e,i)=>{const image=safeWorking(e.working),ai=e.aiAnalysis;return`<article class="panel evidence-card"><div class="evidence-title"><span class="pill ${e.correct?"green":"red"}">${e.correct?"Correct":"Needs review"}</span><small>${TOPICS[e.topic]?.name||safeText(e.topic)}</small></div><h3>${i+1}. ${safeText(e.question)}</h3><p><strong>Learner selected:</strong> ${safeText(e.selectedAnswer??e.choice)}</p>${e.issue?`<p><strong>Possible barrier:</strong> ${safeText(e.issue)}</p>`:""}${ai?`<div class="notice"><strong>AI reading of the working:</strong> ${safeText(ai.transcription||"Not available")}<br><strong>Feedback:</strong> ${safeText(ai.feedback||"—")}<br><strong>Reading confidence:</strong> ${Math.round(Number(ai.confidence||0)*100)}%</div>`:""}${image?`<img class="working-image" src="${image}" alt="Handwritten working for question ${i+1}">`:`<div class="notice">No handwritten working was saved.</div>`}</article>`}).join("")}</div>`)}
async function facilitatorSignOut(){if(cloud)await cloud.auth.signOut();renderHome()}
function exportData(){const payload=JSON.stringify(db.get(),null,2),blob=new Blob([payload],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`grade10-maths-progress-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
function setupCanvas(){const canvas=document.querySelector("#workCanvas");if(!canvas)return;const rect=canvas.getBoundingClientRect(),ratio=Math.max(window.devicePixelRatio||1,1);canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);const ctx=canvas.getContext("2d");ctx.scale(ratio,ratio);ctx.lineCap="round";ctx.lineJoin="round";state.canvas=canvas;state.canvasCtx=ctx;state.eraser=false;state.inkDistance=0;state.strokeCount=0;state.hasWorkingEvidence=false;const point=e=>{const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};canvas.addEventListener("pointerdown",e=>{e.preventDefault();state.drawing=true;state.strokeCount++;state.lastPoint=point(e);canvas.setPointerCapture(e.pointerId)});canvas.addEventListener("pointermove",e=>{if(!state.drawing)return;e.preventDefault();const p=point(e),pressure=e.pressure||.5,dx=p.x-state.lastPoint.x,dy=p.y-state.lastPoint.y;if(!state.eraser)state.inkDistance+=Math.sqrt(dx*dx+dy*dy);ctx.globalCompositeOperation=state.eraser?"destination-out":"source-over";ctx.strokeStyle="#102a43";ctx.lineWidth=state.eraser?22:Math.max(2,pressure*5);ctx.beginPath();ctx.moveTo(state.lastPoint.x,state.lastPoint.y);ctx.lineTo(p.x,p.y);ctx.stroke();state.lastPoint=p;if(!state.hasWorkingEvidence&&state.strokeCount>=2&&state.inkDistance>=100)unlockAnswers()});const stop=()=>{state.drawing=false;state.lastPoint=null};canvas.addEventListener("pointerup",stop);canvas.addEventListener("pointercancel",stop)}
function unlockAnswers(){state.hasWorkingEvidence=true;document.querySelectorAll(".answer-choice").forEach(b=>b.disabled=false);const status=document.querySelector("#workingStatus"),gate=document.querySelector("#answerGate");if(status)status.textContent="Working recorded. You may now choose your answer.";if(gate){gate.textContent="Your answer choices are now unlocked.";gate.classList.add("ready")}}
function setCanvasTool(eraser){state.eraser=eraser;document.querySelector("#penBtn")?.classList.toggle("active",!eraser);document.querySelector("#eraseBtn")?.classList.toggle("active",eraser)}
function clearCanvas(){if(!state.canvasCtx||!state.canvas)return;state.canvasCtx.clearRect(0,0,state.canvas.width,state.canvas.height);state.inkDistance=0;state.strokeCount=0;state.hasWorkingEvidence=false;document.querySelectorAll(".answer-choice").forEach(b=>b.disabled=true);const status=document.querySelector("#workingStatus"),gate=document.querySelector("#answerGate");if(status)status.textContent="Write in the space before choosing an answer.";if(gate){gate.textContent="Complete enough written working to unlock the answers.";gate.classList.remove("ready")}}
function captureCanvas(){return state.canvas?state.canvas.toDataURL("image/webp",.55):null}
function saveSupportEvidence(item,choice,correct,working,issue,aiAnalysis){if(!state.profile)return;const learners=db.get(),key=state.profile.name.toLowerCase(),record=learners.find(l=>l.name.toLowerCase()===key);if(!record)return;const evidence={topic:item.topic,question:item.text,selectedAnswer:item.options[choice],correctAnswer:item.options[item.answer],correct,issue,working,aiAnalysis,date:new Date().toISOString()};record.supportEvidence=record.supportEvidence||[];record.supportEvidence.push(evidence);db.set(learners);state.profile=record;submitOnlineRecord({learner_name:record.name,class_name:record.className,record_type:"targeted_support",topic:item.topic,overall_score:correct?100:0,topic_scores:{[item.topic]:correct?100:0},evidence:[evidence]})}
function diagnosticIssue(item,correct,analysis){if(analysis&&analysis.errorCategory&&analysis.errorCategory!=="correct_method")return errorLabel(analysis.errorCategory);return correct?null:(item.skill||ISSUE_BY_TOPIC[item.topic])}
function errorLabel(value){return({sign_error:"signs",arithmetic_error:"arithmetic calculation",formula_selection:"formula selection",substitution_error:"substitution",algebraic_manipulation:"algebraic manipulation",units:"units",geometry_reason:"geometry reason",probability_rule:"probability rule",unreadable:"unclear handwriting",insufficient_working:"insufficient working",other:"another method difficulty",review_required:"facilitator review required"})[value]||String(value).replaceAll("_"," ")}
async function analyseMathsWorking(item,choice,imageDataUrl){
 try{
  if(!cloud)throw new Error("Offline");
  const{data,error}=await cloud.functions.invoke("analyse-maths-working",{body:{question:item.text,expectedAnswer:item.options[item.answer],selectedAnswer:item.options[choice],topic:TOPICS[item.topic].name,imageDataUrl}});
  if(error)throw error;
  if(!data?.analysis)throw new Error(data?.error||"No analysis returned");
  return data.analysis;
 }catch(error){console.warn("AI handwriting check unavailable:",error.message);return null}
}
async function submitOnlineRecord(record){try{if(!cloud)throw new Error("Offline");const{error}=await cloud.from("learning_records").insert(record);if(error)throw error}catch(error){console.warn("Online save pending:",error.message);const pending=JSON.parse(localStorage.getItem("mathsPathwayPending")||"[]");pending.push(record);localStorage.setItem("mathsPathwayPending",JSON.stringify(pending))}}
function safeText(value){const div=document.createElement("div");div.textContent=String(value??"");return div.innerHTML}
function safeWorking(value){return typeof value==="string"&&/^data:image\/(webp|png);base64,[A-Za-z0-9+/=]+$/.test(value)?value:""}
renderHome();
