const TOPICS={
 algebra:{name:"Algebraic expressions",term:1,summary:"Real numbers, expansion, factorisation and algebraic fractions",worked:"Factorise x² − 5x + 6 by finding two numbers that multiply to 6 and add to −5. They are −2 and −3, so x² − 5x + 6 = (x − 2)(x − 3)."},
 equations:{name:"Exponents & equations",term:1,summary:"Exponent laws, equations, inequalities and changing the subject",worked:"For 2³ × 2⁴, keep the base and add the exponents: 2³⁺⁴ = 2⁷ = 128."},
 trig:{name:"Trigonometry",term:1,summary:"Trig ratios, special angles and right-angled triangles",worked:"If opposite = 6 and hypotenuse = 10, sin θ = 6/10 = 0.6. Therefore θ = sin⁻¹(0.6) ≈ 36.9°."},
 euclidean:{name:"Euclidean geometry",term:2,summary:"Triangles, quadrilaterals, midpoint theorem and riders",worked:"Opposite sides of a parallelogram are parallel and equal. Use these properties together with angle facts, and always give a reason for each statement."},
 analytical:{name:"Analytical geometry",term:2,summary:"Distance, gradient and midpoint",worked:"Between A(2,1) and B(6,9), gradient = (9−1)/(6−2) = 8/4 = 2. The midpoint is ((2+6)/2,(1+9)/2) = (4,5)."},
 functions:{name:"Functions & graphs",term:2,summary:"Shape, domain, range, intercepts, asymptotes and transformations",worked:"For y = 2x − 4, the y-intercept is −4. Set y=0 to find the x-intercept: 0=2x−4, so x=2."},
 statistics:{name:"Statistics",term:3,summary:"Central tendency, spread, quartiles, box plots and histograms",worked:"For 2, 3, 3, 7, 10: mean=25/5=5, median=3, mode=3 and range=10−2=8."},
 probability:{name:"Probability",term:3,summary:"Relative frequency, Venn diagrams, unions and complements",worked:"If P(A)=0.55, P(B)=0.35 and P(A and B)=0.15, then P(A or B)=0.55+0.35−0.15=0.75."},
 finance:{name:"Finance & growth",term:3,summary:"Simple and compound growth in real contexts",worked:"For R2 000 invested at 8% compound interest for 3 years: A=2000(1.08)³=R2 519.42."},
 measurement:{name:"Measurement",term:4,summary:"Surface area and volume of three-dimensional objects",worked:"A cylinder with r=3 cm and h=5 cm has volume V=πr²h=π(3²)(5)=45π≈141.37 cm³."},
 patterns:{name:"Number patterns",term:4,summary:"Linear patterns and general terms",worked:"In 5, 8, 11, 14, … the common difference is 3. Tₙ=3n+2 because T₁=5."}
};
const QUESTIONS=[
 q("algebra","Which is the factorised form of x² − 9?",["(x−9)(x+1)","(x−3)(x+3)","(x−3)²","x(x−9)"],1,"Use the difference of two squares: a²−b²=(a−b)(a+b)."),
 q("algebra","Simplify 3x(2x − 5).",["6x²−15x","6x−15","5x²−15x","6x²−5"],0,"Multiply 3x by every term inside the bracket."),
 q("equations","Simplify a⁵ ÷ a².",["a¹⁰","a⁷","a³","a²⋅⁵"],2,"When dividing like bases, subtract exponents."),
 q("equations","Solve 3x − 7 = 11.",["x=4","x=6","x=8","x=18"],1,"Add 7 to both sides, then divide by 3."),
 q("trig","In a right triangle, which ratio is opposite/hypotenuse?",["tan θ","cos θ","sin θ","sec θ"],2,"SOH: sin = opposite ÷ hypotenuse."),
 q("trig","If tan θ = 1 and 0°≤θ≤90°, what is θ?",["30°","45°","60°","90°"],1,"tan 45°=1."),
 q("euclidean","The diagonals of a parallelogram…",["are always equal","bisect each other","meet at 90° always","never intersect"],1,"A core parallelogram property is that its diagonals bisect one another."),
 q("euclidean","Angles on a straight line add up to…",["90°","180°","270°","360°"],1,"A straight angle measures 180°."),
 q("analytical","Find the gradient through (1,2) and (5,10).",["1/2","2","4","8"],1,"m=(10−2)/(5−1)=8/4=2."),
 q("analytical","Find the midpoint of (2,4) and (8,10).",["(5,7)","(6,6)","(10,14)","(3,9)"],0,"Average the x-values and the y-values separately."),
 q("functions","What is the y-intercept of y=3x−6?",["3","−6","2","−2"],1,"At the y-intercept x=0."),
 q("functions","Which graph has an asymptote at x=0?",["y=x","y=x²","y=1/x","y=2x+1"],2,"The hyperbola y=1/x is undefined at x=0."),
 q("statistics","Find the median of 2, 4, 7, 9, 12.",["4","6.8","7","9"],2,"The median is the middle ordered value."),
 q("statistics","Find the range of 5, 8, 13, 19.",["11","14","19","45"],1,"Range=maximum−minimum=19−5."),
 q("probability","A fair die is rolled. P(even number) is…",["1/6","1/3","1/2","2/3"],2,"There are 3 even outcomes out of 6."),
 q("probability","If P(A)=0.3, what is P(not A)?",["0.3","0.5","0.7","1.3"],2,"Complementary probabilities add to 1."),
 q("finance","Which formula represents compound growth?",["A=P(1+in)","A=P(1+i)ⁿ","A=P+i+n","A=Pin"],1,"Compound growth applies the growth factor repeatedly."),
 q("finance","R1 000 grows by 10% simple interest for 2 years. A is…",["R1 100","R1 200","R1 210","R2 000"],1,"A=P(1+in)=1000(1+0.10×2)."),
 q("measurement","The volume of a cylinder is…",["πr²h","2πr","πrh","⅓πr²h"],0,"Volume of a cylinder=area of circular base×height."),
 q("measurement","If every dimension doubles, volume is multiplied by…",["2","4","6","8"],3,"Volume changes by k³, so 2³=8."),
 q("patterns","Find the next term: 4, 9, 14, 19, …",["20","23","24","29"],2,"The constant difference is 5."),
 q("patterns","For Tₙ=4n−1, find T₅.",["15","19","20","21"],1,"Substitute n=5: 4(5)−1=19.")
];
function q(topic,text,options,answer,help){return{topic,text,options,answer,help}}
const state={view:"home",profile:null,quiz:[],index:0,answers:[],workings:[],supportTopic:null,practiceIndex:0,canvas:null,canvasCtx:null,drawing:false,eraser:false,lastPoint:null};
const app=document.querySelector("#app"),homeBtn=document.querySelector("#homeBtn");
const db={get:()=>JSON.parse(localStorage.getItem("mathsPathwayLearners")||"[]"),set:v=>localStorage.setItem("mathsPathwayLearners",JSON.stringify(v))};
homeBtn.onclick=()=>renderHome();
function shell(content,showHome=true){app.innerHTML=content;homeBtn.classList.toggle("hidden",!showHome);window.scrollTo({top:0,behavior:"smooth"})}
function renderHome(){state.view="home";shell(`<section class="hero"><span class="eyebrow">Know your gaps. Build your confidence.</span><h1>Your personalised Grade 10 Maths pathway.</h1><p>Start with a short diagnostic. The app finds the topics that need attention and gives you focused support, worked examples and practice.</p><div class="role-grid"><button class="role-card" onclick="showLearnerStart()"><span class="role-icon">✦</span><h3>I’m a learner</h3><p>Take a diagnostic or continue your support pathway.</p><span class="btn">Start learning</span></button><button class="role-card" onclick="showDashboard()"><span class="role-icon">◫</span><h3>Facilitator dashboard</h3><p>View learner mastery, gaps and recommended next steps.</p><span class="btn gold">Open dashboard</span></button></div></section>`,false)}
function showLearnerStart(){const learners=db.get();shell(`<div class="screen-head"><div><span class="eyebrow">Learner space</span><h2>Let’s find your next step</h2></div></div><section class="panel form-card"><div class="field"><label>Your name</label><input id="learnerName" placeholder="Enter first and last name"></div><div class="field"><label>Class</label><select id="learnerClass"><option>Grade 10.1</option><option>Grade 10.2</option><option>Grade 10</option></select></div><button class="btn" onclick="beginDiagnostic()">Begin diagnostic</button>${learners.length?`<p class="muted">Returning learner? Use the same name to update your profile.</p>`:""}</section>`)}
function beginDiagnostic(){const name=document.querySelector("#learnerName").value.trim();if(!name)return alert("Please enter the learner’s name.");state.profile={name,className:document.querySelector("#learnerClass").value};state.quiz=[...QUESTIONS].sort(()=>Math.random()-.5);state.index=0;state.answers=[];state.workings=[];renderQuestion()}
function workingCanvas(){return `<div class="working-wrap"><div class="working-head"><strong>Show your working</strong><div class="canvas-tools"><button id="penBtn" class="tool-btn active" onclick="setCanvasTool(false)">Pen</button><button id="eraseBtn" class="tool-btn" onclick="setCanvasTool(true)">Eraser</button><button class="tool-btn" onclick="clearCanvas()">Clear</button></div></div><canvas id="workCanvas" class="work-canvas"></canvas><div class="working-note">Use your Apple Pencil or finger. Your working will be saved with this attempt.</div></div>`}
function renderQuestion(){const item=state.quiz[state.index],pct=Math.round(state.index/state.quiz.length*100);shell(`<div class="screen-head"><div><span class="eyebrow">Diagnostic</span><h2>Question ${state.index+1} of ${state.quiz.length}</h2></div><span class="pill orange">${TOPICS[item.topic].name}</span></div><div class="progress-track"><div class="progress-bar" style="width:${pct}%"></div></div><section class="panel" style="margin-top:20px"><p class="question">${item.text}</p>${workingCanvas()}<div class="options">${item.options.map((o,i)=>`<button class="option" onclick="chooseAnswer(${i})">${String.fromCharCode(65+i)}. ${o}</button>`).join("")}</div><p class="muted">Choose the answer you believe is correct. It’s okay not to know—this helps build the right pathway.</p></section>`);setupCanvas()}
function chooseAnswer(choice){const item=state.quiz[state.index];state.workings.push(captureCanvas());state.answers.push({topic:item.topic,correct:choice===item.answer,choice});state.index++;state.index<state.quiz.length?renderQuestion():finishDiagnostic()}
function finishDiagnostic(){const totals={};Object.keys(TOPICS).forEach(k=>totals[k]={correct:0,total:0});state.answers.forEach(a=>{totals[a.topic].total++;if(a.correct)totals[a.topic].correct++});const scores={};Object.entries(totals).forEach(([k,v])=>scores[k]=v.total?Math.round(v.correct/v.total*100):0);const overall=Math.round(state.answers.filter(a=>a.correct).length/state.answers.length*100);const weakest=Object.keys(scores).sort((a,b)=>scores[a]-scores[b])[0];const learners=db.get(),key=state.profile.name.toLowerCase();const evidence=state.answers.map((a,i)=>({...a,question:state.quiz[i].text,working:state.workings[i]}));const record={...state.profile,lastAttempt:new Date().toISOString(),overall,scores,recommended:weakest,attempts:1,evidence};const old=learners.find(l=>l.name.toLowerCase()===key);if(old)record.attempts=(old.attempts||0)+1;db.set([...learners.filter(l=>l.name.toLowerCase()!==key),record]);state.profile=record;renderResults()}
function band(n){return n>=75?["Secure","green"]:n>=50?["Developing","orange"]:["Priority","red"]}
function renderResults(){const p=state.profile,ordered=Object.keys(p.scores).sort((a,b)=>p.scores[a]-p.scores[b]);shell(`<div class="screen-head"><div><span class="eyebrow">Your pathway</span><h2>${p.name}, here’s what we found</h2></div></div><section class="panel"><div class="result-top"><div class="score-ring" style="--score:${p.overall}"><strong>${p.overall}%</strong></div><div><h3>Diagnostic complete</h3><p class="muted">Your first recommended focus is <strong>${TOPICS[p.recommended].name}</strong>. This is a starting point—not a label.</p><button class="btn" onclick="openSupport('${p.recommended}')">Start targeted support</button></div></div></section><div class="cards"><section class="panel"><h3>Topic map</h3>${ordered.map(k=>{const [label,color]=band(p.scores[k]);return`<div class="topic-row"><div><strong>${TOPICS[k].name}</strong><br><small class="muted">Term ${TOPICS[k].term}</small></div><div class="mini-track"><span style="width:${p.scores[k]}%"></span></div><span class="pill ${color}">${label}</span></div>`}).join("")}</section><section class="panel"><h3>Recommended pathway</h3>${ordered.slice(0,4).map((k,i)=>`<div class="lesson-step"><small class="eyebrow">Step ${i+1}</small><h3>${TOPICS[k].name}</h3><p class="muted">${TOPICS[k].summary}</p><button class="btn secondary" onclick="openSupport('${k}')">Open support</button></div>`).join("")}</section></div>`)}
function openSupport(topic){state.supportTopic=topic;const t=TOPICS[topic],practice=QUESTIONS.filter(q=>q.topic===topic);shell(`<div class="screen-head"><div><span class="eyebrow">Targeted support · Term ${t.term}</span><h2>${t.name}</h2><p class="muted">${t.summary}</p></div></div><div class="cards"><section class="panel"><span class="pill orange">1 · Understand</span><h3 style="margin-top:14px">Worked example</h3><div class="worked equation">${t.worked}</div></section><section class="panel"><span class="pill green">2 · Practise</span><h3 style="margin-top:14px">Check your understanding</h3><p class="question">${practice[0].text}</p>${workingCanvas()}<div class="options">${practice[0].options.map((o,i)=>`<button class="option" onclick="supportAnswer(${i},0)">${o}</button>`).join("")}</div><div id="supportFeedback"></div></section></div><section class="panel" style="margin-top:16px"><span class="pill green">3 · Reflect</span><h3 style="margin-top:12px">Can you explain the method?</h3><p class="muted">Write the steps in your own words. Add any question you still have to your notebook for the Maths teacher.</p><button class="btn secondary" onclick="renderResults()">Return to my pathway</button></section>`);setupCanvas()}
function supportAnswer(choice,idx){const item=QUESTIONS.filter(q=>q.topic===state.supportTopic)[idx],ok=choice===item.answer;saveSupportEvidence(item,choice,ok,captureCanvas());document.querySelector("#supportFeedback").innerHTML=`<div class="answer-feedback ${ok?"correct":"incorrect"}"><strong>${ok?"Correct—well done.":"Not yet—use the clue and try again."}</strong><br>${item.help}</div>`}
function showDashboard(){const learners=db.get();const avg=learners.length?Math.round(learners.reduce((s,l)=>s+l.overall,0)/learners.length):0;const priority=learners.filter(l=>l.overall<50).length;shell(`<div class="screen-head"><div><span class="eyebrow">Facilitator view</span><h2>Grade 10 Maths dashboard</h2><p class="muted">Diagnostic evidence and suggested support—not formal assessment marks.</p></div><button class="btn secondary" onclick="exportData()">Export learner data</button></div><div class="stat-grid"><div class="card stat"><span class="muted">Learners diagnosed</span><strong>${learners.length}</strong></div><div class="card stat"><span class="muted">Average mastery</span><strong>${avg}%</strong></div><div class="card stat"><span class="muted">Priority support</span><strong>${priority}</strong></div></div><section class="panel" style="margin-top:18px"><h3>Learner profiles</h3>${learners.length?`<div class="table-wrap"><table class="learner-table"><thead><tr><th>Learner</th><th>Class</th><th>Mastery</th><th>Priority topic</th><th>Attempts</th><th>Last activity</th></tr></thead><tbody>${learners.sort((a,b)=>a.overall-b.overall).map(l=>`<tr><td><strong>${l.name}</strong></td><td>${l.className}</td><td><span class="pill ${band(l.overall)[1]}">${l.overall}%</span></td><td>${TOPICS[l.recommended].name}</td><td>${l.attempts}</td><td>${new Date(l.lastAttempt).toLocaleDateString()}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty"><h3>No diagnostic results yet</h3><p>Once learners complete the diagnostic, their profiles will appear here.</p></div>`}</section><div class="notice" style="margin-top:16px"><strong>Pilot note:</strong> Data is saved on this browser. Use “Export learner data” to back it up or send it to the Maths teacher.</div>`)}
function exportData(){const payload=JSON.stringify(db.get(),null,2),blob=new Blob([payload],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`grade10-maths-progress-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
function setupCanvas(){const canvas=document.querySelector("#workCanvas");if(!canvas)return;const rect=canvas.getBoundingClientRect(),ratio=Math.max(window.devicePixelRatio||1,1);canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);const ctx=canvas.getContext("2d");ctx.scale(ratio,ratio);ctx.lineCap="round";ctx.lineJoin="round";state.canvas=canvas;state.canvasCtx=ctx;state.eraser=false;const point=e=>{const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};canvas.addEventListener("pointerdown",e=>{e.preventDefault();state.drawing=true;state.lastPoint=point(e);canvas.setPointerCapture(e.pointerId)});canvas.addEventListener("pointermove",e=>{if(!state.drawing)return;e.preventDefault();const p=point(e),pressure=e.pressure||.5;ctx.globalCompositeOperation=state.eraser?"destination-out":"source-over";ctx.strokeStyle="#102a43";ctx.lineWidth=state.eraser?22:Math.max(2,pressure*5);ctx.beginPath();ctx.moveTo(state.lastPoint.x,state.lastPoint.y);ctx.lineTo(p.x,p.y);ctx.stroke();state.lastPoint=p});const stop=()=>{state.drawing=false;state.lastPoint=null};canvas.addEventListener("pointerup",stop);canvas.addEventListener("pointercancel",stop)}
function setCanvasTool(eraser){state.eraser=eraser;document.querySelector("#penBtn")?.classList.toggle("active",!eraser);document.querySelector("#eraseBtn")?.classList.toggle("active",eraser)}
function clearCanvas(){if(!state.canvasCtx||!state.canvas)return;state.canvasCtx.clearRect(0,0,state.canvas.width,state.canvas.height)}
function captureCanvas(){return state.canvas?state.canvas.toDataURL("image/webp",.55):null}
function saveSupportEvidence(item,choice,correct,working){if(!state.profile)return;const learners=db.get(),key=state.profile.name.toLowerCase(),record=learners.find(l=>l.name.toLowerCase()===key);if(!record)return;record.supportEvidence=record.supportEvidence||[];record.supportEvidence.push({topic:item.topic,question:item.text,choice,correct,working,date:new Date().toISOString()});db.set(learners);state.profile=record}
renderHome();
